language: node_js
node_js:
- '5'
- '4.2'

script: npm run citest
after_script: npm install coveralls@^2.11.9 && cat ./coverage/lcov.info | coveralls

before_deploy:
- npm run bootstrap
- tsc --outDir .